name: 'Checkmarx AST CLI Action'
description: 'Simplify Checkmarx Scanning of source code along with Result consumption leveraging Checkmarx AST solution.'
author: 'Checkmarx Technical Services'
inputs:
  base_uri:
    required: true
    description: 'Provide the AST portal URL'
    default: 'http://demo.ast-cloud.com'
  client_id:
    required: true
    description: 'Client ID for AST portal authentication'
    default: ' '
  secret:
    required: true
    description: 'Secret key for AST portal authentication'
    default: ' '
  project_type:
    required: false
    description: 'Project type for AST'
    default: 'sast'
  project_name:
    required: false
    default: ${{ github.repository }} # default repo name
    description: 'Select a Checkmarx Project Name'
  github_token:
    required: false
    default: ${{ github.token }}
    description: 'GitHub API Token'
  archive_source:
    required: false
    default: ' '
    description: 'Source for the Zip file'
  source_directory:
    required: false
    default: '.'
    description: 'Source for the project directory'
  filter:
    required: false
    default: ' '
    description: 'Project scan filters for AST'
  additional_params:
    required: false
    default: ' '
    description: 'Additional parameters for AST scan'
runs:
  using: 'docker'
  image: 'Dockerfile'
#  args:
#    - --base-uri ${{ inputs.base_uri }}
#    - -- client-id ${{ inputs.client_id }}
#    - --secret ${{ inputs.secret }}
#    - --project-type ${{ inputs.project_type }}
#    - --project-name ${{ inputs.project_name }}
#    - ${{ inputs.github_token }}
#    - --archive-source ${{ inputs.archive_source }}
#    - --project-source ${{ inputs.project_source }}
#    - --additional-parameters ${{ inputs.additional_params }}

  env:
    BASE_URI: "${{ inputs.base_uri }}"
    CLIENT_ID: ${{ inputs.client_id }}
    SECRET: ${{ inputs.secret }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    PROJECT_TYPE: ${{ inputs.project_type }}
    PROJECT_NAME: ${{ inputs.project_name }}
    ARCHIVE_SOURCE: ${{ inputs.archive_source }}
    SOURCE_DIRECTORY: ${{ inputs.source_directory }}
    ADDITIONAL_PARAMS: ${{ inputs.additional_params }}
    FILTER: ${{ inputs.filter }}

branding:
  icon: 'check'
  color: 'green'
