name: 'Checkmarx AST CLI Action'
description: 'Simplify Checkmarx Scanning of source code along with Result consumption leveraging Checkmarx AST solution.'
author: 'Checkmarx Technical Services'
inputs:
  base_uri:
    required: true
    description: 'Provide the AST portal URL'
    default: 'http://demo.ast-cloud.com'
  client_id:
    required: false
    description: 'Client ID for AST portal authentication'
    default: ''
  secret:
    required: false
    description: 'Secret key for AST portal authentication'
    default: ''
  token:
    required: false
    description: 'Token for AST portal authentication'
    default: ''
  project_type:
    required: false
    description: 'Project type for AST'
    default: 'sast'
  project_name:
    required: false
    default: ${{ github.repository }} # default repo name
    description: 'Select a Checkmarx Project Name'
  github_token:
    required: false
    default: ${{ github.token }}
    description: 'GitHub API Token'
  archive_source:
    required: false
    default: ''
    description: 'Source for the Zip file'
  source_directory:
    required: false
    default: '.'
    description: 'Source for the project directory'
  filter:
    required: false
    default: '.'
    description: 'Project scan filters for AST'
  additional_params:
    required: false
    default: ''
    description: 'Additional parameters for AST scan'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base_uri }}
    - ${{ inputs.client_id }}
    - ${{ inputs.secret }}
    - ${{ inputs.token }}
    - ${{ inputs.github_token }}
    - ${{ inputs.project_type }}
    - ${{ inputs.project_name }}
    - ${{ inputs.archive_source }}
    - ${{ inputs.source_directory }}
    - ${{ inputs.additional_params }}
    - ${{ inputs.filter }}

  env:
    CX_BASE_URI: "${{ inputs.base_uri }}"
    CX_AST_ACCESS_KEY_ID: ${{ inputs.client_id }}
    CX_AST_ACCESS_KEY_SECRET: ${{ inputs.secret }}
    CX_TOKEN: ${{ inputs.token }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    PROJECT_TYPE: ${{ inputs.project_type }}
    PROJECT_NAME: ${{ inputs.project_name }}
    ARCHIVE_SOURCE: ${{ inputs.archive_source }}
    SOURCE_DIRECTORY: ${{ inputs.source_directory }}
    ADDITIONAL_PARAMS: ${{ inputs.additional_params }}
    FILTER: ${{ inputs.filter }}

branding:
  icon: 'check'
  color: 'green'
